"""Flat-harness bundle generation.

Four of the seven supported harnesses cannot follow a reference: Codex has no
import directive, ForgeCode injects its rules as an already-rendered value,
Gemini rejects imports that resolve outside the extension root, and Pi's
ambient slot is a single file. They receive a concatenation of the selected
modules written at the harness's real instruction path.

The artifact is always regenerated from the current selection, never patched.
A regenerated artifact cannot drift out of step with the selection; a patched
one can.
"""

from __future__ import annotations

import re
from dataclasses import dataclass, field
from pathlib import Path
from typing import Dict, List, Optional, Sequence, Tuple

from .rule_modules import RuleModule

# Per-module provenance. Parsed by tests to assert "exactly these modules, in
# this order, and nothing else" rather than substring-searching, which passes
# on a superset.
MODULE_MARKER_PREFIX = "<!-- spellbook-module:"

# The single delivery marker, emitted once inside the core module's region.
# A distinct prefix from the per-module marker so the two are never confused.
DELIVERY_MARKER_PREFIX = "<!-- spellbook-rules:"

MODULE_MARKER_RE = re.compile(
    r"^<!-- spellbook-module: (?P<id>[a-z][a-z0-9-]*) \(source: (?P<source>[^,]+), "
    r"v(?P<version>[^)]*)\) -->$"
)

# The module that carries the delivery marker. Mandatory, so it is present in
# every possible selection.
MARKER_MODULE_ID = "core"

# Per-platform bundle caps. None means the harness imposes no cap on what
# spellbook writes -- verified for all four flat harnesses. The drop machinery
# below is a safety net against a cap being lowered by configuration, not a
# response to a truncation defect that exists today.
PLATFORM_BUNDLE_CAPS: Dict[str, Optional[int]] = {
    "codex": None,
    "forgecode": None,
    "gemini": None,
    "pi": None,
}


class BundleTooLargeError(RuntimeError):
    """The mandatory module set alone exceeds the platform's cap.

    Raised rather than truncating. A truncated ruleset is a ruleset whose
    contents nobody can predict.
    """


@dataclass
class BundleResult:
    """One generated flat-harness artifact."""

    content: str
    platform: str
    included_ids: List[str] = field(default_factory=list)
    dropped: List[Tuple[str, int]] = field(default_factory=list)
    cap: Optional[int] = None

    @property
    def size_bytes(self) -> int:
        return len(self.content.encode("utf-8"))

    def drop_report(self) -> List[str]:
        """Human-readable lines naming every dropped module and the cap.

        Printed to the installer's normal output, never only to a debug log:
        a bundle that quietly lost a module is the failure this reports.
        """
        if not self.dropped:
            return []
        lines = [
            f"{self.platform}: bundle exceeded the {self.cap}-byte cap; "
            f"dropped {len(self.dropped)} preference module(s), largest first:"
        ]
        lines.extend(f"  - {mod_id} ({size} bytes)" for mod_id, size in self.dropped)
        return lines


def delivery_marker(version: str) -> str:
    """The tripwire marker string for a given spellbook version."""
    return f"{DELIVERY_MARKER_PREFIX} {MARKER_MODULE_ID} v{version} -->"


def module_marker(module: RuleModule, version: str) -> str:
    """The per-module provenance marker for a given module."""
    return (
        f"{MODULE_MARKER_PREFIX} {module.id} "
        f"(source: rules/{module.source_name}, v{version}) -->"
    )


def banner(version: str) -> str:
    """The generated-artifact banner.

    This is the one place a do-not-edit notice is warranted: the flat artifact
    is the only hand-editable copy of the ruleset a user ever sees.
    """
    return (
        f"<!-- Generated by spellbook {version}. "
        "Edits are overwritten on the next install. -->\n"
        "<!-- Source: rules/*.md in the spellbook checkout. "
        "Edit those, then re-run install. -->"
    )


def parse_bundle_module_ids(content: str) -> List[str]:
    """Return the module ids a generated bundle declares, in order."""
    ids: List[str] = []
    for line in content.splitlines():
        match = MODULE_MARKER_RE.match(line.strip())
        if match:
            ids.append(match.group("id"))
    return ids


def _render(modules: Sequence[RuleModule], version: str) -> str:
    parts = [banner(version)]
    for module in modules:
        parts.append("")
        parts.append(module_marker(module, version))
        if module.id == MARKER_MODULE_ID:
            parts.append(delivery_marker(version))
        parts.append("")
        parts.append(module.body.rstrip())
    return "\n".join(parts).rstrip() + "\n"


def generate_bundle(
    modules: Sequence[RuleModule],
    version: str,
    platform: str,
    cap: Optional[int] = None,
) -> BundleResult:
    """Concatenate the selected modules into one flat-harness artifact.

    Modules arrive in delivery order and are emitted in that order. When a cap
    applies and the artifact exceeds it, preference modules are dropped
    largest-first until it fits; mandatory modules are never dropped.

    Raises:
        BundleTooLargeError: the mandatory set alone exceeds ``cap``.
    """
    if cap is None:
        cap = PLATFORM_BUNDLE_CAPS.get(platform)

    ordered = list(modules)
    content = _render(ordered, version)

    if cap is None or len(content.encode("utf-8")) <= cap:
        return BundleResult(
            content=content,
            platform=platform,
            included_ids=[m.id for m in ordered],
            cap=cap,
        )

    dropped: List[Tuple[str, int]] = []
    droppable = sorted(
        (m for m in ordered if m.is_preference),
        key=lambda m: (-m.size_bytes, m.id),
    )

    for candidate in droppable:
        dropped.append((candidate.id, candidate.size_bytes))
        ordered = [m for m in ordered if m.id != candidate.id]
        content = _render(ordered, version)
        if len(content.encode("utf-8")) <= cap:
            return BundleResult(
                content=content,
                platform=platform,
                included_ids=[m.id for m in ordered],
                dropped=dropped,
                cap=cap,
            )

    raise BundleTooLargeError(
        f"{platform}: the mandatory rule modules alone are "
        f"{len(content.encode('utf-8'))} bytes, over the {cap}-byte cap. "
        "Refusing to truncate."
    )


def bundle_contains_marker(path: Path, version: str) -> bool:
    """Whether a written artifact carries this version's delivery marker."""
    try:
        return delivery_marker(version) in path.read_text(encoding="utf-8")
    except OSError:
        return False
