"""MEMORY.md regenerator for bridging Claude Code auto-memory with spellbook.

Generates a hybrid MEMORY.md containing bootstrap instructions (directing the
model to use spellbook MCP tools) and a brief summary of key memories from
the structured store.
"""

from collections import defaultdict
from pathlib import Path
from typing import Optional

from spellbook.core.branch_ancestry import get_current_branch
from spellbook.core.db import get_db_path
from spellbook.core.path_utils import encode_cwd, resolve_repo_root
from spellbook.memory.tools import do_log_event, do_memory_recall


_HEADER = """\
# Project Memory (spellbook-managed)

<!-- This file is auto-generated by spellbook on session init.
     Manual edits will be captured and incorporated into spellbook's
     structured memory, then overwritten on the next session start. -->

## How to Use Memory

For persistent memory storage, prefer spellbook MCP tools over editing this file:

- **Store:** `memory_store_memories` with structured JSON
- **Recall:** `memory_recall` with keyword queries or file paths
- **Review:** `memory_get_unconsolidated` for pending raw events

Writes to this file are automatically captured by spellbook's bridge hook
and fed into the structured memory system.
"""

# Header is ~18 lines. Budget: 200 total, ~20 header, ~30 safety margin = 150 for content.
_MAX_TOTAL_LINES = 200
_HEADER_LINES = len(_HEADER.strip().split("\n"))
_SAFETY_MARGIN = 30
_MAX_SUMMARY_LINES = _MAX_TOTAL_LINES - _HEADER_LINES - _SAFETY_MARGIN


def generate_memory_md(
    db_path: str,
    project_path: str,
    namespace: str,
    branch: str = "",
    max_summary_lines: int = _MAX_SUMMARY_LINES,
) -> str:
    """Generate MEMORY.md content: bootstrap instructions + memory summary.

    Args:
        db_path: Path to spellbook.db
        project_path: Project root for context
        namespace: Project-encoded namespace for memory_recall
        branch: Current git branch for branch-weighted scoring
        max_summary_lines: Max lines for the summary section

    Returns:
        Complete MEMORY.md content as a string.
    """
    repo_path = resolve_repo_root(project_path) or project_path

    result = do_memory_recall(
        db_path=db_path,
        query="",
        namespace=namespace,
        limit=20,
        branch=branch,
        repo_path=repo_path,
    )

    memories = result.get("memories", [])
    if not memories:
        return _HEADER.rstrip() + "\n"

    # Group memories by type
    groups: dict[str, list[str]] = defaultdict(list)
    for mem in memories:
        mem_type = mem.get("memory_type", "general") or "general"
        content = mem.get("content", "").strip()
        if content:
            groups[mem_type].append(content)

    # Render summary section
    summary_lines: list[str] = ["", "## Key Memories", ""]
    line_count = 0

    # Sort groups for deterministic output
    for mem_type in sorted(groups.keys()):
        items = groups[mem_type]
        # Section header: capitalize the type
        header = f"### {mem_type.replace('_', ' ').title()}"
        # Check if adding this group would exceed budget
        # header (1) + blank (1) + items (N) + trailing blank (1)
        group_lines = 3 + len(items)
        if line_count + group_lines > max_summary_lines:
            summary_lines.append(
                "<!-- Truncated. Use memory_recall for full access. -->"
            )
            break

        summary_lines.append(header)
        summary_lines.append("")
        for item in items:
            # Single-line bullet; truncate long items
            bullet = f"- {item[:200]}"
            summary_lines.append(bullet)
            line_count += 1
            if line_count >= max_summary_lines:
                summary_lines.append(
                    "<!-- Truncated. Use memory_recall for full access. -->"
                )
                break
        else:
            summary_lines.append("")
            line_count += 3  # header + blank before + blank after
            continue
        break  # Inner break triggered truncation

    return _HEADER.rstrip() + "\n" + "\n".join(summary_lines) + "\n"


def _resolve_auto_memory_dir(project_path: str) -> Optional[Path]:
    """Resolve the Claude Code auto-memory directory for a project.

    Claude Code uses: ~/.claude/projects/<project-encoded>/memory/
    where project-encoded = path with leading / removed, slashes -> dashes,
    prefixed with a dash.
    """
    home = Path.home()
    encoded = project_path.lstrip("/").replace("/", "-")

    # Primary: with leading dash (Claude Code's format)
    memory_dir = home / ".claude" / "projects" / f"-{encoded}" / "memory"
    if memory_dir.is_dir():
        return memory_dir

    # Fallback: without leading dash
    alt_dir = home / ".claude" / "projects" / encoded / "memory"
    if alt_dir.is_dir():
        return alt_dir

    return None


def _bootstrap_existing_memory_md(
    memory_dir: Path, db_path: str, namespace: str
) -> None:
    """One-time: capture existing MEMORY.md content before first regeneration."""
    marker = memory_dir / ".spellbook-bridge-initialized"
    if marker.exists():
        return

    memory_md = memory_dir / "MEMORY.md"
    if memory_md.exists():
        content = memory_md.read_text(encoding="utf-8")
        if content.strip() and "spellbook-managed" not in content:
            do_log_event(
                db_path=db_path,
                session_id="bootstrap",
                project=namespace,
                tool_name="auto_memory_bridge",
                subject=str(memory_md),
                summary=content[:10000],
                tags="auto-memory,bridge,bootstrap,memory.md",
                event_type="auto_memory_bridge",
                branch="",
            )

    marker.write_text("initialized", encoding="utf-8")


def regenerate_memory_md_for_project(project_path: str) -> None:
    """Regenerate MEMORY.md for a project's auto-memory directory.

    Resolves the auto-memory directory path, bootstraps existing content
    if needed, generates content via generate_memory_md, and writes the file.
    Fail-open: exceptions do not propagate.
    """
    try:
        memory_dir = _resolve_auto_memory_dir(project_path)
        if not memory_dir:
            return

        db_path = str(get_db_path())
        namespace = encode_cwd(project_path)
        repo_path = resolve_repo_root(project_path) or project_path
        branch = get_current_branch(repo_path) if repo_path else ""

        # One-time bootstrap of pre-existing content
        _bootstrap_existing_memory_md(memory_dir, db_path, namespace)

        content = generate_memory_md(
            db_path=db_path,
            project_path=project_path,
            namespace=namespace,
            branch=branch,
        )

        memory_md_path = memory_dir / "MEMORY.md"
        memory_md_path.write_text(content, encoding="utf-8")
    except Exception:
        pass  # Fail-open: never block session init
