/** @type {import('tailwindcss').Config} */
import typography from '@tailwindcss/typography'

export default {
  content: ['./index.html', './src/**/*.{ts,tsx}'],
  theme: {
    extend: {
      typography: {
        // Element opt-outs (design §2.1): these elements are owned by the
        // per-element React overrides (canvas/components.tsx), so the
        // typography plugin must emit NO competing rule for them. These live
        // under DEFAULT (not invert) because the base `.prose :where(elem)`
        // rules are generated by the DEFAULT theme; the invert modifier only
        // overrides color vars on top. Nulling a selector key drops the
        // generated rule entirely. Verified by spike/css-probe.mjs.
        DEFAULT: {
          css: {
            a: false,
            'a:hover': false,
            code: false,
            'code::before': false,
            'code::after': false,
            pre: false,
            table: false,
            thead: false,
            tfoot: false,
            // The plugin keys table-cell rules under compound selectors, not
            // bare th/td/tr, so the bare keys do not drop them. Null the exact
            // compound keys the plugin emits (verified against the installed
            // @tailwindcss/typography styles + spike/css-probe.mjs).
            'thead th': false,
            'thead th:first-child': false,
            'thead th:last-child': false,
            'tbody tr': false,
            'tbody tr:last-child': false,
            'tbody td': false,
            'tfoot td': false,
            'tbody td, tfoot td': false,
            'tbody td:first-child, tfoot td:first-child': false,
            'tbody td:last-child, tfoot td:last-child': false,
            'th, td': false,
          },
        },
        // Dark-token prose theme: map the typography plugin's invert CSS
        // variables onto the existing canvas tokens so `prose prose-invert`
        // reads legibly on #050505.
        invert: {
          css: {
            '--tw-prose-invert-body': '#f0ebe4',
            '--tw-prose-invert-headings': '#b4f461',
            '--tw-prose-invert-links': '#61f4e8',
            '--tw-prose-invert-bold': '#f0ebe4',
            '--tw-prose-invert-bullets': '#787068',
            '--tw-prose-invert-hr': '#2a2a2a',
            '--tw-prose-invert-quotes': '#a09a90',
            '--tw-prose-invert-quote-borders': '#2a2a2a',
            '--tw-prose-invert-code': '#61f4e8',
            '--tw-prose-invert-th-borders': '#2a2a2a',
            '--tw-prose-invert-td-borders': '#2a2a2a',
          },
        },
      },
      colors: {
        'bg-primary': '#050505',
        'bg-surface': '#0e0e0e',
        'bg-elevated': '#161616',
        'bg-border': '#2a2a2a',
        'text-primary': '#f0ebe4',
        'text-secondary': '#a09a90',
        'text-dim': '#787068',
        'accent-green': '#b4f461',
        'accent-cyan': '#61f4e8',
        'accent-amber': '#f4c761',
        'accent-red': '#f46161',
      },
      fontFamily: {
        mono: ['JetBrains Mono', 'Fira Code', 'monospace'],
        sans: ['Inter', 'system-ui', 'sans-serif'],
      },
    },
  },
  plugins: [typography],
}
